# This workflow uses actions that are not certified by GitHub.
# They are provided by a third-party and are governed by
# separate terms of service, privacy policy, and support
# documentation.

name: Flutter

on:
  push:
    branches: [ "main", "dev" ]
    paths:                                                                                                                                                       
      - 'lib/**'                                                                                                                                                 
      - 'pubspec.*'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Clone repository
        uses: actions/checkout@v6

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Download dependencies
        run: flutter pub get

      - name: Analyze the code
        run: flutter analyze

      - name: Build debug
        run: flutter build apk --debug

      - name: Run tests
        uses: w9jds/firebase-action@master
        with:
          args: apptesting:execute --app=1:354833570442:android:8ded6af77bac9d6039ab73  --test-dir=./tests ./build/app/outputs/apk/debug/app-debug.apk
        env:
          GCP_SA_KEY: ${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}
