name: Publish to Google Play

on:
  push:
    tags:
      - '*'
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v6

      - name: Set up JDK
        uses: actions/setup-java@v5
        with:
          distribution: 'zulu'
          java-version: '21'
          cache: 'gradle'

      - name: Set up Flutter
        uses: subosito/flutter-action@v2
        with:
          channel: stable

      - name: Download dependencies
        run: flutter pub get

      - name: Decode keystore
        run: echo "${{ secrets.ANDROID_KEYSTORE_BASE64 }}" | base64 -d > android/upload-keystore.jks

      - name: Decode google-services.json                                                                             
        run: echo "${{ secrets.GOOGLE_SERVICES_JSON_BASE64 }}" | base64 -d > android/app/google-services.json

      - name: Write key.properties
        run: echo "${{ secrets.ANDROID_KEY_PROPERTIES }}" > android/key.properties

      - name: Build AAB
        run: flutter build appbundle --release

      - name: Publish to Google Play
        uses: r0adkll/upload-google-play@v1
        with:
          serviceAccountJsonPlainText: ${{ secrets.GOOGLE_PLAY_SERVICE_ACCOUNT_JSON }}
          packageName: 'com.chaplyk.memory'
          releaseFile: 'build/app/outputs/bundle/release/app-release.aab'
          track: 'internal'
          status: 'completed'
